### PR TITLE
coding style tweaks and new ext. registration function

### PR DESCRIPTION
**Pull request by codynguyen1116**
New extension registration & skin function in favor of using extension.json / skin.json instead of extension-name.php or skin-name.php files

### CODE REVIEW

**Comment by codynguyen1116** [comment]
3rd pull request and I looked over everything three times so I think this is good to go. :P

**Comment by UltrasonicNXT** [comment]
Btw you should now be able to commit directly yourself :)

**Comment by codynguyen1116** [comment]
Thanks Adam! I appreciate it :D

**Comment by UltrasonicNXT** [comment]
No worries :)

**Pull request merged**
