### PR TITLE
replace ext:videoflash with ext:embedvideo

### PR DESCRIPTION
**Pull request by codyn329**

### CODE REVIEW

**Comment by georgebarnick** [comment]
I thought we were going to use Extension:YouTube instead? And if you can, put in a commit to Brickimedia/extensions to add whatever new extension we choose to use.

**Comment by codyn329** [comment]
I decided Extension:EmbedVideo (https://www.mediawiki.org/wiki/Extension:EmbedVideo) because it seems more flexible and also provides support for 24 services of video content; and it can also utilize template parameters easily since it's a parser function. If we want to though instead, we can use Extension:YouTube (https://www.mediawiki.org/wiki/Extension:YouTube).

**Comment by georgebarnick** [comment]
Waiting for commit to Brickimedia/extensions

**Comment by codyn329** [comment]
Sorry, I can't add an extension since I don't know how to.

**Comment by georgebarnick** [comment]
Clone Brickimedia/extensions and in its directory ```git submodule add https://github.com/wikimedia/mediawiki-extensions-ExtensionName ExtensionName```

Optionally (but suggested), specify the branch for the submodule by
```bash
git submodule init
git submodule update
cd ExtensionName
git checkout REL1_24
```

**Comment by georgebarnick** [comment]
You're free to ask questions in wiki chat or IRC any time too

**Comment by georgebarnick** [comment]
Closing this as we don't want to remove VideoFlash until everything is converted to EmbedVideo format, and as the source repository for this pull request was deleted, it can't be modified.

**Comment by ALittleSlow** [comment]
What exactly needs to be converted? Do we need to change all VideoFlash references in articles to Embed Video references *before* the extension is installed? Why can't the two extensions co-exist until the conversion is complete? Thanks.

**Comment by georgebarnick** [comment]
@ALittleSlow: What I want is for them to be coexist until the references on the wikis have been converted. Been waiting on @UltrasonicNXT to fix whatever is preventing EmbedVideo from even being added, but have not gotten a response from him on Skype in a while...

**Comment by UltrasonicNXT** [comment]
@georgebarnick what's up?

**Comment by georgebarnick** [comment]
```shell
$ git submodule init
$ git submodule update
error: Untracked working tree file 'tests/browser/config/config.yml' would be ov
erwritten by merge.
Unable to checkout '09b0174734a14934997623c9ecd019345d3938e1' in submodule path
'Translate'
```

Therefore it's impossible to add EmbedVideo... I told you this on Skype a few days ago also..

**Comment by UltrasonicNXT** [comment]
Okay, fixed this issue, something dodgy with translate, ```/update.sh``` is working fine now.

**Comment by georgebarnick** [comment]
:+1:

**Comment by georgebarnick** [comment]
EmbedVideo still doesn't seem to be cloned as a submodule. It's there when viewing ```ls``` but it's not a directory as if it hasn't been cloned or something. What's up with that?

image

**Comment by UltrasonicNXT** [comment]
check out https://github.com/Brickimedia/extensions, it's not a submodule

**Comment by georgebarnick** [comment]
Oh... Can you make it one Adam?

**Comment by UltrasonicNXT** [comment]
done

**Comment by UltrasonicNXT** [comment]
right looks like we're just a require_once away from installing this...

**Comment by UltrasonicNXT** [comment]
Installed, but I've left VideoFlash for the mo so as not to break anything

**Comment by ALittleSlow** [comment]
Tested and working on http://greatballcontraption.com/wiki/GBC:Manual_of_Style#Embedded_Video

**Comment by ALittleSlow** [comment]
Thanks, everybody!

**Pull request closed without merging**
